scss/core/base.scss
Ref. https://github.com/Fliplet/fliplet-studio/issues/2367
The theme shouldn’t have a static value setting, that doesn’t come from the user.
Also, this button style override already exists in `bootstrap.css`.
=> Removes padding override from theme

scss/core/base.scss, theme.json
This resolves the following problems:
- There are too many settings for tables
- No user has needed to apply different border styles to the 4 sides (top, bottom, left, right).
- No user has needed to apply different border styles to table or table rows. They are most likely just changing the border color
It also adds styling support for class-less tables following https://github.com/Fliplet/fliplet-api/pull/2823
=> Simplifies configurations for tables

scss/core/menu.scss
Because of this change: https://github.com/Fliplet/fliplet-menu-bottom-bar/pull/8
=> Change the target of the background color

scss/components/lists-data-source.scss
Resolves the following problems, where the blue buttons/borders should be in dark navy:
=> Makes sure search and filter UI are correctly themed

scss/components/chat.scss
Issue reported by @ibroom on LMA app where links posted on blue colored bubbles are invisible.
=> fixes links color in bubbles

scss/components/interactive-graphics.scss
To be released with: https://github.com/Fliplet/fliplet-widget-interactive-map/pull/38
=> Fix input color on search field

theme.json
Fix for: https://github.com/Fliplet/fliplet-studio/issues/4574
This will be used to ignore selectors using jquery `.not()`
=> Allow to ignore certain selectors

scss/components/forms.scss
For the following: https://github.com/Fliplet/fliplet-studio/issues/4576
There were some missing properties for the form labels.
=> Missing properties for form labels

theme.json
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4670
This PR adds a hidden configuration that the sole purpose is to make available to custom SCSS the old variables from the previous theme version.
=> Adds a hidden configuration to contain old variables

theme.json
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4670
To fix the menus styles. This PR makes the Push In, Slide In, and Swipe menus to inherit styles from the Overlay menu.
Before we didn't have those menu types separated and now we have, but to keep styles configured by the user on v1 theme this change needs to happen.
=> Fixes defaults for menus

scss/components/forms.scss
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4723
- Added support for time and date fields
=> Fixes date and time fields padding

theme.json
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4723
- Prevent `padding-left` on Date and Time fields to change in real time
- This is because the `padding-left` property for these fields need an extra `45px` to be added and we do not have a system to do that in real time.
=> Prevent padding-left on Date and Time fields to change in real time

scss/components/buttons.scss
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4787
Before the new version of the theme was created, the `interact.css` would control the `width` of inline components to be `100%` on mobile, but because now the user can control those properties we had to remove them from `interact.css`.
This fix makes the buttons `width: 100%` on mobile. This is only for Theme v1.
=> Force buttons to be full width on mobile

scss/components/links.scss, theme.json
By fixing the following issue, https://github.com/Fliplet/fliplet-studio/issues/5510, I have noticed that it was impossible to set normal font styles to links, on both old and new drag and drop systems.
This change addresses that problem.
=> Added more options for inline links

scss/components/body.scss, scss/components/text.scss, theme.json
- Fixes defaults for headings font weight in the Text component
- Fixes default Container width for tablet
- Issue ref: https://github.com/Fliplet/fliplet-studio/issues/5507
- Fixes default Text display for tablet
- Fixes variable names on Text
- Issue ref: https://github.com/Fliplet/fliplet-studio/issues/5506
- Fixes the correct default values for the `display` property
- Issue ref: https://github.com/Fliplet/fliplet-studio/issues/5512
- Changes to all heading `margin-bottom` property in the Text component
- Issue ref: https://github.com/Fliplet/fliplet-studio/issues/5511
=> Fixes and tweaks

theme.json
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/5647
The `min-height` was too high, creating a bad experience for some uses that wanted to add small elements inside the container component.
=> Set min-height of containers to 20px

scss/components/lists-data-source.scss
https://github.com/Fliplet/fliplet-studio/issues/5710
Works with https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/311/commits/fd682685a6371c82c517296a0dbcde350ef20256 to make sure max-width is not applied to the container for the Agenda layout.
=> Ensures agenda max-width is applied correctly

theme.json
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/5816
- This will prevent users using the old D&D system from hiding components and not being able to retrieve them.
=> Show Visibility option on apps that support containers

scss/components/app-list.scss, theme.json
https://github.com/Fliplet/fliplet-studio/issues/4319
User can now edit color of warning message and apps title.
=> User can now configure text color in app list

theme.json
https://github.com/Fliplet/fliplet-studio/issues/4734
Onboarding text color now inherits general text color which inherits quick settings color.
=> Onboarding text color now inherits general text color

scss/components/notification-inbox.scss, theme.json
https://github.com/Fliplet/fliplet-studio/issues/4693
Added possibility to change background for published in-app notifications.
=> Users now can change background for published in-app notifications

scss/components/forms.scss, theme.json
https://github.com/Fliplet/fliplet-studio/issues/4724
Updated selectors.
Goes together with this PR https://github.com/Fliplet/fliplet-widget-form-builder/pull/270
=> Border properties now affect rich text field

scss/components/images.scss
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/5937
- Image components will act as expected inside and outside flex containers
=> Fix images responsiveness when inside flex containers on IE11

scss/components/forms.scss, theme.json
https://github.com/Fliplet/fliplet-studio/issues/4724
Tinymce border-radius is also changing when using brush icon.
=> Tinymce border radius can be set by brush icon

scss/components/lists-data-source.scss
https://github.com/Fliplet/fliplet-studio/issues/6151
The issue was that selector was not specific enough.
=> Simple list filters now looks correctly

scss/components/accordions.scss
https://github.com/Fliplet/fliplet-studio/issues/5721
I only added lines 130-132 to have the same styles applied both in edit and preview modes.
=> Accordion styles now are applied correctly

scss/components/menu-push-in.scss
https://github.com/Fliplet/fliplet-studio/issues/6575
Fixed selectors in scss file.
=> [Fix] Appearance settings work correctly on menu style 'push in' with button on left

theme.json
https://github.com/Fliplet/fliplet-studio/issues/6526
Inherited old LFD variables in all layouts.
Now all layouts inherit old LFD values where it needed so old users shouldn't fill any problems with the new features.
=> [Feature] Inherited old LFD variables in all layouts.

theme.json
https://github.com/Fliplet/fliplet-studio/issues/6524
Fixed type error.
Removed `!` from appearance text.
=> [Fix] Fixed type error.

theme.json
https://github.com/Fliplet/fliplet-studio/issues/6609
Changed layouts order to avoid inheritance issues.
Changed order according to this [comment](https://github.com/Fliplet/fliplet-studio/issues/6609#issuecomment-645278417)
=> [Fix] Changed layouts order to avoid inheritance issues.

scss/components/forms.scss, theme.json
https://github.com/Fliplet/fliplet-studio/issues/6624
The default color will be background color from quick settings.
https://streamable.com/qxe6pe
=> [Feature] Added possibility to change background color of signature field

scss/components/forms.scss, theme.json
https://github.com/Fliplet/fliplet-studio/issues/6490
Added possibility to change styles text and placeholders of inputs.
Live changes on placeholders do not work and apparently there is no way to make them work.
=> [Feature] Added possibility to change styles text and placeholders of inputs

scss/components/forms.scss, theme.json
https://github.com/Fliplet/fliplet-studio/issues/6588
Added possibility to style "clear" text in the signature field and error message.
Also fixed some labels according to Ian's comment.
https://streamable.com/mauh1b
=> [Feature] Added possibility to style extra fields in form builder

scss/core/base.scss, theme.json
Fliplet/fliplet-studio#6420
To achieve outline only on focus by keyboard (and not on click) we are also checking if the element is not hovered. In the component, we then have to just add class "outline-item-selector" to the element we want to focus.
https://streamable.com/sgegno
=> [Feauture] Added possibility to style outlines

scss/core/base.scss, theme.json
Fliplet/fliplet-studio#6420
Sorry to bother again but we need an extra line of focus-within to target some pieces where input lies inside of label to which we need add box-shadow.
=> [Fix] Focus-within-outline

scss/components/lfd/news-feed.scss, scss/components/lfd/simple-list.scss, scss/components/lfd/small-card.scss
https://github.com/Fliplet/fliplet-studio/issues/6858
Users will see filters text in overlay mode
https://share.getcloudapp.com/9ZuXA4Nk
=> [Fix] Users will see filters text in overlay mode

scss/components/lfd/agenda.scss, scss/components/lfd/news-feed.scss, scss/components/lfd/small-card.scss
https://github.com/Fliplet/fliplet-studio/issues/6858
Made filters overlay looks the same in all layouts. 
https://share.getcloudapp.com/4gu91d52
=> [Fix] Made overlay filters looks the same in all layouts. 

scss/components/buttons.scss
https://github.com/Fliplet/fliplet-studio/issues/6948
The primary button will change only on click.
https://share.getcloudapp.com/5zuGdzdJ
=> [Fix] The primary button will change only on click.

scss/core/base.scss
https://github.com/Fliplet/fliplet-studio/issues/6424
Removed outline for touchable devices.
=> [Fix] Remove outline on touch devices when user taps on focussable UI

scss/core/base.scss
https://weboo.atlassian.net/browse/OD-83
Removed native outline for the touchable devices.
https://share.getcloudapp.com/Blu17XQO
=> [Fix] OD-83 Removed native outline for the touchable devices.

js/focus-visible.js, scss/core/base.scss, theme.json
https://weboo.atlassian.net/browse/OD-198
Accordions will not have a box-shadow on click.
https://share.getcloudapp.com/mXu6xpER - IE11
https://share.getcloudapp.com/X6udReYD - Chrome
For correct work on IE11 and Safari, this [polyfill](https://github.com/WICG/focus-visible) needs to be installed.
=> [Fix] OD-198 Accordions will not have a box-shadow on click.

scss/core/base.scss
https://weboo.atlassian.net/browse/OD-426
Removed `!important` from `box-shadow: none` to allow the use of the default box-shadow when an element isn't selected by the Tab key.
https://share.getcloudapp.com/Koudze08
@upplabs-alex-levchenko @ivandevupp @AndrRyaz
=> OD-426 [Fix] Users will see correct box-shadow when element isn't hovered.

scss/core/base.scss
https://weboo.atlassian.net/browse/OD-426
Removed unneeded `!important` for tablet and desktop views.
https://share.getcloudapp.com/WnuYwrO0
@upplabs-alex-levchenko @ivandevupp
=> OD-426 [Fix] Users will be able to see default box shadows on the tablet and desktops.

theme.json
OD-337 https://weboo.atlassian.net/browse/OD-337
Made all line height fields in all appearances have a list of units that includes the "x" unit by fixing config names.
https://monosnap.com/file/T3Go6vyRW7tpKGAOBxaGshNqQPW7zL
@upplabs-alex-levchenko @AndrRyaz @YaroslavOvdii
=> OD-337 [Fix] Make all line height fields in all appearances have a list of units that includes the "x" unit

scss/components/lfd/small-card.scss, scss/components/lfd/small-h-card.scss
https://weboo.atlassian.net/browse/OD-158
Corrected selectors for the detail view icons color
https://share.getcloudapp.com/7KuoBrzk
To work correctly needs this [PR](https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/585) as well
=> OD-158 [Feature] Allow users to set correct detail view icons color

scss/components/lfd/simple-list.scss
https://weboo.atlassian.net/browse/OD-523
Corrected SCSS selector for the arrow in the simple list items
https://share.getcloudapp.com/5zuY74nd
=> OD-523 [Fix] Enable configuration of LFD Simple List arrow color for tablet and desktop

scss/components/lfd/news-feed.scss, scss/components/lfd/simple-list.scss
@sofiiakvasnevska @inna-bieshulia
OD-567 https://weboo.atlassian.net/browse/OD-567
Description
**Problem:** The color of the like counter will not inherit from the color of the like itself.
**Solution:** Styles for the likes count were corrected and inheritance parameters for the counter color were added.
Screenshots/screencasts
https://storyxpress.co/video/ktk0v0y0m2i3n8l33
Backward compatibility
Reviewers
=> OD-567 [Fix] Fix Like counter color to match appearance settings

theme.json
@romanyosyfiv
OD-52 https://weboo.atlassian.net/browse/OD-52
**Problem**: "Add" button color on Agenda was not inherited from the main button
**Solution**: "Add" button color on Agenda inherit from the main button by analogy with other LFT components
https://storyxpress.co/video/kvmb92yhgjl2ah75c
=> OD-52 [Fix] Fixed "Add" button color on Agenda

scss/components/lfd/news-feed.scss, scss/components/lfd/simple-list.scss
@romanyosyfiv @inna-bieshulia
OD-639 https://weboo.atlassian.net/browse/OD-639
##Description
**Problem:** Styles are not added for app sorting arrows that inherit from highlight color.
**Solution:** Styles were added for app sorting arrows that inherit color from highlight color.
https://storyxpress.co/video/kwvwv5v7etgpes0if
=> OD-639 [Fix] Adjusted appearance settings to the in-app sorting arrows for News Feed and Simple List

scss/components/chat.scss
@romanyosyfiv
OD-730 https://weboo.atlassian.net/browse/OD-730
**Problem**: The default text color of the inactive button was as white as its background.
**Solution**: By default, the text color of the inactive button is use the color of the button border.
=> OD-730 [Fix] Fixed text color for button

theme.json
**Product areas affected**
Primary Button->Edit appearance settings-> WIDTH AND HEIGHT
Primary Button->Edit appearance settings-> POSITIONING
**What does this PR do?**
button width and no row sharing positioning properties inherit from mobile to tablet and tablet to desktop. In this PR we are updated the width and positioning for tablet preview as per the mobile settings.
**JIRA ticket**
[click here](https://weboo.atlassian.net/browse/XOR-82)
**Result**
https://user-images.githubusercontent.com/102005879/179494407-8daa6ab6-9240-4b60-a4cf-e39a6d49dfc0.mp4
**Checklist**
None
**Testing instructions**
None
**Deployment instructions**
None
**Author concerns**
None
=> XOR-82 [FIX] Ensure button style and no row sharing positioning settings update in tablet preview

theme.json
**Product areas affected**
Secondary Button->Edit appearance settings-> WIDTH AND HEIGHT
Secondary Button->Edit appearance settings-> POSITIONING
**What does this PR do?**
button width and no row sharing positioning properties inherit from mobile to tablet and tablet to desktop. In this PR we are updated the width and positioning for tablet preview as per the mobile settings.
**JIRA ticket**
[click here](https://weboo.atlassian.net/browse/XOR-308)
**Result**
https://user-images.githubusercontent.com/102005879/181274743-9a26b4e8-7bb6-4426-80f9-b4b9e55b2b33.mp4
**Checklist**
None
**Testing instructions**
None
**Deployment instructions**
None
**Author concerns**
None
=> XOR-308 [Fix] Ensure button style and no row sharing positioning settings update in tablet preview

scss/components/forms.scss
Widgets -> Add Form -> Star Field -> Select / Unselect Star ->  Make field read only
Implemented code to apply readonly text background and selected fill color to Readonly star field correctly.
[JIRA](https://weboo.atlassian.net/browse/XOR-156)
https://user-images.githubusercontent.com/108272606/194356277-679723f4-3514-45b9-808d-7d36d6a4c3e4.mp4
None
None
None
=> XOR-156 [Fix] Ensure Readonly Star field has correct readonly colors

scss/components/container.scss, scss/components/intro-layout.scss, scss/components/text.scss
Ref. https://weboo.atlassian.net/browse/ID-2629
When `url()` is used alongside `#{}` it appears that it doesn't take `,` within unless `""` is added around it.
This fixes the problem where the `map-get()` wasn't getting a second parameter, which breaks the theme compilation.
I've verified the error no longer occurs and the image background feature for containers is working as expected.
=> ID-2629 [Fix] Fix container background CSS compilation issue caused by formatters

scss/components/forms.scss
Widgets -> Form  -> Dropdown field -> Required -> Submit Form
Implemented fix so that in Form component, when submitting the dropdown fields (required), its border style is matching with error state 
[JIRA](https://weboo.atlassian.net/browse/XOR-663)
https://user-images.githubusercontent.com/108272606/228447109-0676cdd1-177a-4fe1-aead-bc153d24b609.mp4
none
none
none
none
=> XOR-663 [Fix] Ensure dropdown fields are styled correctly when they are invalid

theme.json
I have added new logic to hide and show the `auto` option from `margin-left` and `margin-right` fields
https://www.loom.com/share/ab02ede13925497d95db04afc40e38b9?sid=8dbad969-9114-4340-8938-c957245c3ece
=> ID-3723 [FIX] Fixing image centering issue

scss/components/lfd/small-card.scss
Fliiplet Theme Default
Ensures the search field background color transparency is applied to the component.
[PS-40](https://weboo.atlassian.net/browse/PS-40)
[PS-40]: https://weboo.atlassian.net/browse/PS-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PS-40 [FIX]: Ensures the search field background color transparency is applied to the component.
