- scss/components/lists.scss
- theme.json
[never mind the branch name]
- Fixes https://github.com/Fliplet/fliplet-studio/issues/1333
- Updates styles to include the new App List component
> Fixes and updates

- scss/components/accordions.scss
Fixes: https://github.com/Fliplet/fliplet-studio/issues/1494
> Fixes issue 1494

- scss/components/directories.scss
- scss/core/base.scss
- theme.json
for https://github.com/Fliplet/fliplet-widget-theme/pull/6
> helvetica as base font

- scss/core/base.scss
- theme.json
This allows the following scenarios:
> Adds support for table and row border styling (without individual axes)

- scss/components/lists-data-source.scss
ref: https://github.com/Fliplet/fliplet-studio/issues/3189
> Fixes for new agenda component

- scss/components/forms.scss
Corrects theming for:
- Date and time fields
- Signature field
- WYSIWYG field
> Corrects form theming for various fields

- scss/components/forms.scss
> Adds border styling support to TinyMCE mobile

- scss/components/lists-data-source.scss
- theme.json
To allow point number one here: https://github.com/Fliplet/fliplet-studio/issues/3433
Also fixes some style bugs.
> Added options for LFD

- scss/core/menu.scss
Change required by: https://github.com/Fliplet/fliplet-menu-bottom-bar/pull/10
> Adds background color to different bottom menu element

- scss/components/chat.scss
- Support for Load More button introduced in https://github.com/Fliplet/fliplet-widget-chat/pull/39
> Support for new Load More contacts button

- scss/components/chat.scss
- Adds support for group chat selectors
- Removes unnecessary styling
> Updates theme to support chat enhancements

- scss/components/chat.scss
Follows https://github.com/Fliplet/fliplet-widget-chat/pull/55
> Restores background color for search and user bars

- scss/components/forms.scss
Updated for https://github.com/Fliplet/fliplet-widget-form-builder/pull/164
> Updates styling based on form UI changes

- scss/components/lists-data-source.scss
Simple list
News feed
Directory
Agenda
> Style bookmark icons according to primary button colors

- theme.json
- Increased version of Fliplet theme
> Version increase

- theme.json
Fixes for: https://github.com/Fliplet/fliplet-studio/issues/4576
> Added missing selector

- scss/components/lists-data-source.scss
- theme.json
For the following: https://github.com/Fliplet/fliplet-studio/issues/4573
Added three new options for the agenda layout, and made sure all other options have affect on all layouts in a way that makes sense to the user.
> Tightning some LFD settings

- scss/components/panels.scss
- scss/core/mixins.scss
- theme.json
Updates the Grid styles with correct values to the same used before.
> Fixes theme values

- theme.json
- Fixes some inconsistencies with headings
> Theme fixes

- theme.json
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4647
- Another fix for small issues when upgrading from old theme to the new version.
> Hover styles of buttons inherit from normal styles

- scss/components/intro-layout.scss
- Remove static values from theme and move them to layout
- Make selector on theme more specific to be able to overwrite the layout styles
Here is the entire layout CSS that has been adjusted to support apps with old theme and new theme. Please review:
```scss
$introBodyBackground: #337ab7 !default;
$introOverlayColor: rgba(0, 0, 0, 0.5) !default;
$introBodyTextColor: #ffffff !default;
$introLinkColor: #337ab7 !default;
$introLinkHoverColor: #286090 !default;
$introLinkHoverDecor: underline !default;
.container-fluid {
position: relative;
height: 100vh;
background-color: $introBodyBackground;
}
.fl-with-top-menu .container-fluid {
height: calc(100vh - 44px);
}
.container-fluid:not(.fl-intro-layout) {
.panel-overlay {
background: none;
position: absolute;
margin: 0;
border-radius: 0;
top: …
```
> Remove static properties from theme

- scss/components/buttons.scss
- scss/components/charts.scss
- scss/components/directories.scss
- scss/core/base.scss
Issues:
- https://github.com/Fliplet/fliplet-studio/issues/4689
- https://github.com/Fliplet/fliplet-studio/issues/4690
- https://github.com/Fliplet/fliplet-studio/issues/4691
- https://github.com/Fliplet/fliplet-studio/issues/4692
- https://github.com/Fliplet/fliplet-studio/issues/4701
- https://github.com/Fliplet/fliplet-studio/issues/4702
> Theme fixes based on QA testing

- scss/components/accordions.scss
- scss/components/app-list.scss
- scss/components/buttons.scss
- scss/components/charts.scss
- scss/components/chat.scss
- scss/components/directories.scss
- scss/components/forms.scss
- scss/components/images.scss
- scss/components/interactive-graphics.scss
- scss/components/links.scss
- scss/components/list-large.scss
- scss/components/list-small.scss
- scss/components/lists-data-source.scss
- scss/components/lists.scss
- scss/components/lock.scss
- scss/components/login-registration.scss
- scss/components/menu-bottom-bar.scss
- scss/components/menu-circle.scss
- scss/components/menu-overlay.scss
- scss/components/menu-push-in.scss
- scss/components/menu-slide-in.scss
- scss/components/menu-swipe.scss
- scss/components/notification-inbox.scss
- scss/components/panels.scss
- scss/components/photo-sharing.scss
- scss/components/rss.scss
- scss/components/slider.scss
- scss/components/video.scss
- scss/index.scss
- Adds support for the UUID in the mixins
> Added UUID support

- scss/components/images.scss
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4854
- Removes duplicated properties for image components
> Fix image styles

- scss/components/buttons.scss
- scss/components/images.scss
- scss/components/panels.scss
- scss/components/slider.scss
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4862
- There were some missing arguments from some `mixins`
> Missing arguments

- scss/components/directories.scss
- scss/components/forms.scss
- theme.json
- Tweaks and fixes of small issues found by testing the app templates
> Small tweaks

- scss/components/buttons.scss
- scss/components/images.scss
- theme.json
- Added external padding to the button components
- On image components we changed the selector that gets the padding aplied
> Tweaks theme

- scss/components/buttons.scss
- scss/components/container.scss
- scss/components/forms.scss
- scss/components/images.scss
- scss/components/list-large.scss
- scss/components/list-small.scss
- scss/components/lists-data-source.scss
- scss/components/lists.scss
- scss/components/lock.scss
- scss/components/panels.scss
- scss/components/rss.scss
- scss/components/text.scss
- theme.json
- Paragraph and Heading styles for Text components are inherited from the base styles
- Tweaks to defaults
- Added Positioning options to:
- Forms
- List no image
- List small thumbs
- List large thumbs
- LFD
- Lock
- RSS
- Panels
> Theme updates

- theme.json
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/5511#issuecomment-570164766
> Set Text component's margin bottom default to 0px

- theme.json
- requires https://github.com/Fliplet/fliplet-api/pull/3797 
- ref https://github.com/Fliplet/fliplet-studio/issues/5527
> Added widgetInstance reference

- scss/index.scss
Issue ref: https://github.com/Fliplet/fliplet-studio/issues/5529#issuecomment-572975033
> Missing Chart Pie if statement

- scss/components/lists-data-source.scss
Ref. https://github.com/Fliplet/fliplet-studio/issues/3585
> Theme updates for agenda filters

- scss/components/menu-overlay.scss
- scss/components/menu-slide-in.scss
Fliplet/fliplet-studio#6575
Fixed selectors in scss file.
> [Fix] Fixed selectors for "slide in" and "default" menus

- scss/components/lfd/agenda.scss
- scss/components/lfd/news-feed.scss
- scss/components/lfd/simple-list.scss
- scss/components/lfd/small-card.scss
- theme.json
Fliplet/fliplet-studio#6225
Updated defaults according to Hugos comments. 
> [Feature] Updated defaults, added new fields

- theme.json
https://github.com/Fliplet/fliplet-studio/issues/6663
Fixed typo
> [Fix] Fixed bookmark type

- scss/index.scss
Fliplet/fliplet-studio#6664
This PR will be tested by Inna as we do not have previous LFD settings.
> [Fix] Lfd backwards support

- scss/components/lfd/news-feed.scss
- theme.json
Fliplet/fliplet-studio#6530
https://github.com/Fliplet/fliplet-studio/issues/6685
Fixed typos.
Fixed news feed errors.
> [Fix] News feed fixes

- scss/components/lfd/small-card.scss
- theme.json
https://github.com/Fliplet/fliplet-studio/issues/6719
Fixed mistakes and typos.
> [Fix] Fixed featured List default appearance settings inconsistencies

- theme.json
https://github.com/Fliplet/fliplet-studio/issues/6743
Fixed simple list errors.
> [Fix] Simple list fixes

- theme.json
https://github.com/Fliplet/fliplet-studio/issues/6225
Updated some inheritance according to Hugo's comment.
> [Fix] Updated some small card inheritance values

- scss/core/base.scss
- theme.json
Fliplet/fliplet-studio#6420
We need important to override some bootstrap styling and remove the outline.
> [Fix] Outline fixes

- scss/components/lfd/agenda.scss
- scss/components/lfd/news-feed.scss
- scss/components/lfd/simple-list.scss
- scss/components/lfd/small-card.scss
- scss/components/lfd/small-h-card.scss
- theme.json
https://github.com/Fliplet/fliplet-studio/issues/6807
Updated layout selection according to Hugo's comment. 
> [Fix] Appearance layout improvements

- scss/components/lfd/news-feed.scss
- scss/components/lfd/simple-list.scss
Fliplet/fliplet-studio#6928
Fixed bookmark selectors for news feed and simple list.
> [Fix] Bookmarks fix

- scss/components/lfd/agenda.scss
- scss/components/lfd/small-card.scss
- theme.json
Fliplet/fliplet-studio#6928
Fixed bookmark selectors for small card and agenda layouts.
> [Fix] Bookmarks fix 2

- scss/core/base.scss
- theme.json
Reverted outline theme changes.
> [Revert] Revert outline

- scss/core/base.scss
- theme.json
Added back appearance settings for outlines.
> [Fix] Added back appearance settings for outlines

- scss/components/lfd/agenda.scss
- scss/components/lfd/news-feed.scss
- scss/components/lfd/simple-list.scss
- scss/components/lfd/small-card.scss
- theme.json
Fliplet/fliplet-studio#7014
Updated selectors.
> [Fix] Lfd filters background applies correct colors

- scss/components/lfd/agenda.scss
- scss/components/lfd/news-feed.scss
- scss/components/lfd/simple-list.scss
- scss/components/lfd/small-card.scss
- theme.json
https://weboo.atlassian.net/browse/OD-55?atlOrigin=eyJpIjoiMmFmYTUzYmI5NWJjNGFkMWJiYWQyYTNmZDE5ZTFiZmIiLCJwIjoiaiJ9
Added Add button customization options
https://share.getcloudapp.com/lluYA1g1
> [Fix] Added Add button customization options

- scss/core/base.scss
Fliplet/fliplet-studio#6422
Added static outline class to be used in places like TinyMCE editor
https://streamable.com/fdf290
> [Fix] Added static outline class

- theme.json
requires https://github.com/Fliplet/fliplet-api/pull/4372
> ID-423 [Fix] Reference for media files

- scss/components/lfd/agenda.scss
OD-68 https://weboo.atlassian.net/browse/OD-68
LFD Agenda DateSelector color Tablet and Desktop fixes
https://screencast-o-matic.com/watch/cYl2Dp8o6B
> OD-68 [Fix] LFD Agenda DateSelector color Tablet and Desktop fixes

- scss/components/lfd/news-feed.scss
- scss/components/lfd/simple-list.scss
- scss/components/lfd/small-card.scss
- theme.json
OD-260 https://weboo.atlassian.net/browse/OD-260
Add Sort Icon Color property to LFD(Directory, Simple-list, News-Feed)
https://screencast-o-matic.com/watch/cYl2DF8oVh
> OD-260 [Fix] Add Sort Icon Color property to LFD(Directory, Simple-list, News-Feed)

- scss/components/links.scss
- scss/core/base.scss
OD-137 https://weboo.atlassian.net/browse/OD-137
Apply text link appearance settings to anchors
https://monosnap.com/file/MpBa8FwGlJxdZfkqeqmaMMnQlEVtyz
@AndrRyaz @YaroslavOvdii
> OD-137 [Fix] Apply text link appearance settings to anchors

- scss/components/lfd/agenda.scss
- scss/components/lfd/news-feed.scss
- scss/components/lfd/small-card.scss
- scss/components/lfd/small-h-card.scss
OD-291 https://weboo.atlassian.net/browse/OD-291
Fix LFD List item border radius for Directory, Featured List, News feed and Agenda
https://monosnap.com/file/EK1ljuQX2OwJe6alvt2y9q6IlCcKx6
@upplabs-alex-levchenko @YaroslavOvdii
> OD-291 [Fix] LFD List item border radius

- scss/components/accordions.scss
- theme.json
https://weboo.atlassian.net/browse/OD-348
Added a new section with accordion content background settings to the appearance.
https://share.getcloudapp.com/p9u87kJL
@upplabs-alex-levchenko @ivandevupp
> OD-348 [Fix] Users will be able to set accordion content background

- scss/components/lfd/agenda.scss
https://weboo.atlassian.net/browse/OD-426
Added a more specific CSS selector for the LFD item in the Agenda layout.
https://share.getcloudapp.com/Z4uozWPB
@upplabs-alex-levchenko @ivandevupp @AndrRyaz
> OD-426 [Fix] Users will be able to see box-shadow in the LFD Agenda layout

- scss/core/base.scss
Reverts Fliplet/fliplet-theme-default#161
> Revert "OD-426 [Fix] Users will be able to see default box shadows on the tablet and desktops."

- scss/components/lfd/agenda.scss
Reverts Fliplet/fliplet-theme-default#162
> Revert "OD-426 [Fix] Users will be able to see box-shadow in the LFD Agenda layout"

- scss/components/lfd/agenda.scss
- scss/core/base.scss
https://weboo.atlassian.net/browse/OD-426
Restore preivos fixes
https://share.getcloudapp.com/E0uYgdLG
@upplabs-alex-levchenko @ivandevupp
> OD-426 [Fix] Users will see box-shadow on LFD elements  

- scss/components/lfd/simple-list.scss
https://weboo.atlassian.net/browse/OD-515
Fixed variable name for the simple list layout in the appearance 
https://share.getcloudapp.com/DOuD5Ld4
> OD-515 [Fix] Users will be able to set correct simple list item color for desktop devices

- scss/components/datepicker.scss
- scss/index.scss
Ref. https://weboo.atlassian.net/browse/ID-1376
> ID-1376 [Feat] Add theme support for date picker

- scss/components/datepicker.scss
Ref. https://weboo.atlassian.net/browse/ID-1378
> ID-1378 [Feat] Adds accessibility outline support for date pickers

- scss/components/number-input.scss
- scss/index.scss
Ref. https://weboo.atlassian.net/browse/ID-1467
> ID-1467 [Feat] Make number inputs from Fliplet.UI.NumberInput themeable

- scss/components/datetime.scss
- scss/index.scss
Ref. https://weboo.atlassian.net/browse/ID-1783
> ID-1783 [Feat] Add accessibility highlight for date/time pickers

- scss/components/lfd/agenda.scss
- scss/components/lfd/news-feed.scss
- scss/components/lfd/simple-list.scss
- scss/components/lfd/small-card.scss
@romanyosyfiv @inna-bieshulia
OD-643 https://weboo.atlassian.net/browse/OD-643
**Problem:** Styles for LFD search result bubble did not inherit from highlight color.
**Solution:** Added style inheritance from highlight color.
www.awesomescreenshot.com/video/7652864?key=c99c3b484801be85558a91929b30a813
> OD-735 [Fix] Fixed styles for search result bubble

- theme.json
Ref. https://weboo.atlassian.net/browse/ID-2103
> ID-2103 [Fix] Adds media file reference for global settings

- scss/components/lfd/agenda.scss
- scss/components/lfd/news-feed.scss
- scss/components/lfd/simple-list.scss
- scss/components/lfd/small-card.scss
- scss/components/lfd/small-h-card.scss
@romanyosyfiv @inna-bieshulia
OD-758 https://weboo.atlassian.net/browse/OD-758
> OD-758 [Fix] Added styles for LFD message when there are no results

- scss/components/lfd/agenda.scss
- scss/components/lfd/news-feed.scss
- scss/components/lfd/simple-list.scss
- scss/components/lfd/small-card.scss
- theme.json
@romanyosyfiv
OD-387 https://weboo.atlassian.net/browse/OD-387
Added settings for background color and text color to search field
https://user-images.githubusercontent.com/86256215/152752276-663bd1ae-b535-408a-b7ec-a94ef0752ba3.mp4
> OD-387 [Fix] Added settings for search field background and text colors

- scss/core/mixins.scss
- scss/index.scss
Ref. https://weboo.atlassian.net/browse/ID-2202
> ID-2202 [Maintenance] Updated to support Dart based sass engine upgrade

- scss/components/forms.scss
Ref. https://weboo.atlassian.net/browse/ID-1781
Requires https://github.com/Fliplet/fliplet-api/pull/5340
> ID-1781 [Feat] Support styling for Date field in Form component

- scss/components/forms.scss
Ref. https://weboo.atlassian.net/browse/ID-1784
Requires https://github.com/Fliplet/fliplet-api/pull/5394
> ID-1784 [Feat] Support styling for Time field in Form component

- scss/components/login-registration.scss
- theme.json
Reverts Fliplet/fliplet-theme-default#192
> Revert "Revert "OD-514 [Fix] Updated section Login & Registration""

- scss/components/interactive-graphics.scss
- theme.json
Ref. https://weboo.atlassian.net/browse/ID-2723
> ID-2723 [Fix] Update default minimum height

- scss/components/forms.scss
- scss/components/range-slider.scss
- scss/index.scss
- theme.json
Widgets -> Add Form -> Add Slider field -> Theme Appearance Settings -> Form -> Slider field settings
Implemented code to add theme appearance settings for Slider field
[JIRA](https://weboo.atlassian.net/browse/XOR-303)
https://user-images.githubusercontent.com/108272606/200500372-cdb6c8e9-88ea-4d6f-9987-772c32015fed.mp4
None
None
None
> XOR-303 [FEAT] Added theme appearance settings for Slider field

- scss/components/interactive-graphics.scss
- scss/components/lfd/agenda.scss
- theme.json
- ID-2723 [Fix] Update default minimum height for interactive graphics #203
- ID-2587 [Feat] Update Agenda appearance settings to match other layouts #201
> Release to Production

- scss/components/forms.scss
- theme.json
Widgets -> Add Form -> Add Matrix field -> Theme Appearance Settings -> Form
Implemented code to add theme appearance settings for Matrix field
[JIRA](https://weboo.atlassian.net/browse/XOR-666)
https://user-images.githubusercontent.com/108272606/204784542-98284612-702c-4dcd-955b-e472bec3e571.mp4
None
None
None
> XOR-666 [FEAT] Added theme appearance settings for Matrix field

- scss/components/forms.scss
**Product areas affected**
Studio -> Form -> File / Image
**What does this PR do?**
Implemented code to make image and file buttons as per designs.
**JIRA ticket**
[click here](https://weboo.atlassian.net/browse/XOR-537)
**Result**
https://user-images.githubusercontent.com/108272606/228492617-d6bb01cf-e733-45c9-88e5-3dab27cbf728.mp4
**Checklist**
None
**Testing instructions**
None
**Deployment instructions**
None
**Author concerns**
None
> XOR-537 [FIX] Updates padding and positioning of "+" icon in image and file buttons

- scss/components/login-registration.scss
- theme.json
Styles for new Sign up button on Login component
https://weboo.atlassian.net/browse/ID-4531
> ID-4531 Styles for new Sign up button on Login component

- scss/components/login-registration.scss
- theme.json
Added support for new field labels and Show/Hide icons
https://weboo.atlassian.net/browse/ID-4558
> ID-4558 Added support for new field labels and Show/Hide icons

- scss/components/login-registration.scss
- theme.json
Added support for new field labels and Show/Hide icons
https://weboo.atlassian.net/browse/ID-4558
> Release 20240709

- scss/components/forms.scss
- theme.json
Fliplet theme default
Adds map height customization via settings
[DEV-92](https://weboo.atlassian.net/browse/DEV-92)
[DEV-92]: https://weboo.atlassian.net/browse/DEV-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add map height customization via settings

- scss/core/mixins.scss
https://weboo.atlassian.net/browse/PS-494?focusedCommentId=71601&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-71601
> fix(PS-494): adjust the above and below mixins to properly handle styles on ipad pro 1024px

- scss/components/lfd/agenda.scss
https://weboo.atlassian.net/browse/PS-475
> fix(PS-475): dynamic list agenda rwd

- scss/components/lfd/agenda.scss
https://weboo.atlassian.net/browse/PS-475
> fix(PS-475): add missing rule for lfdv1 agenda template top bar bookmark icon

- scss/components/lfd/agenda.scss
Fliiplet Form Builder
Ensures the Agenda Appearance Settings are thoroughly working.
[PS-760](https://weboo.atlassian.net/browse/PS-760)
[PS-760]: https://weboo.atlassian.net/browse/PS-760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PS-760 [FIX]: Ensures the Agenda Appearance Settings are thoroughly working.
